backend:
  name: github
  repo: dackalacbayo/shuffleph # Path to your Github repository
  branch: master # Branch to update

media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "events"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "By", name: "by", widget: "string"}
<<<<<<< HEAD
      - {label: Dates, name: bdates, widget: list, fields: [{label: Date, name: date, widget: "date", default: "", format: "LL"}]}
=======
      - {label: Dates, name: adates, widget: object, fields: [{label: Dates, name: bdates, widget: list, fields: [{label: Date, name: date, widget: "date", default: "", format: "LL"}]}]}
>>>>>>> a79df450a78f022317115537b9b9b3a2bf50c10e
      # - {label: "Date", name: "date", widget: "date", default: "", format: "LL", multidate: true}
      - {label: "Start time",  name: "start",  widget: "datetime", default: "", format: "hh:mma"}
      - {label: "End time",  name: "end",  widget: "datetime", default: "", format: "hh:mma"}
      - {label: "Description", name: "body", widget: "markdown"}
